# Generated by Django 4.2.4 on 2023-08-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeddata',
            name='air_quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='storeddata',
            name='body_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='storeddata',
            name='env_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='storeddata',
            name='pulse_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='storeddata',
            name='spo2_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='storeddata',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='storeddata',
            name='numerical_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='storeddata',
            name='time',
            field=models.TextField(),
        ),
    ]
